# Generated by Django 5.0.4 on 2024-04-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="article_title",
            field=models.CharField(default="article_2024-04-16_205650", max_length=255),
        ),
    ]
