# Generated by Django 5.0.4 on 2024-04-16 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_article_article_overview_alter_article_article_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_title",
            field=models.CharField(default="article_2024-04-16_222509", max_length=255),
        ),
        migrations.AlterField(
            model_name="content",
            name="article_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.article"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="content_overview",
            field=models.TextField(max_length=255),
        ),
    ]
