# Generated by Django 5.0.4 on 2024-04-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0066_rename_tag_name_tag_name_alter_article_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(default='article_2024-04-30_015507', max_length=255),
        ),
    ]
